version: '3'
services:
  frontend:
      image: ol1ee/ebusiness:latest
      container_name: frontend
      ports:
        - 3000:3000
      command: "npm start"
  backend:
      image: ol1ee/ebusiness:latest
      container_name: backend
      ports:
        - 9000:9000
      command: "sbt run"
